HF_API_TOKEN = "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"
[theme]
base="light"
primaryColor="#F63366"
secondaryBackgroundColor="#f0f2f6"
font="sans serif"

[server]
enableCORS = false

[client]
showSidebarNavigation = true

[ui]
hideTopBar = false
pageTitle = "PixelGenius - AI Art Generator"

